require("dotenv").config({ path: "./.env" }); // تعديل مسار الـ env عشان يرفع على اللايف

const connectDB = require("./src/config/database");
const GlobalFood = require("./src/models/GlobalFood");

const foods = [
  // === البروتينات (اللحوم والطيور) ===
  {
    nameEn: "Chicken Breast (Cooked)",
    nameAr: "صدور دجاج (مطهية)",
    calories: 165,
    protein: 31,
    carbs: 0,
    fats: 3.6,
    baseUnit: "100g",
  },
  {
    nameEn: "Chicken Thigh",
    nameAr: "وراك دجاج (مطهية)",
    calories: 209,
    protein: 26,
    carbs: 0,
    fats: 10.9,
    baseUnit: "100g",
  },
  {
    nameEn: "Chicken Wing",
    nameAr: "جناح دجاج (مطهي)",
    calories: 203,
    protein: 26,
    carbs: 0,
    fats: 10.5,
    baseUnit: "100g",
  },
  {
    nameEn: "Chicken Leg",
    nameAr: "ساق دجاج (مطهية)",
    calories: 215,
    protein: 20,
    carbs: 0,
    fats: 15,
    baseUnit: "100g",
  },
  {
    nameEn: "Ground Chicken",
    nameAr: "دجاج مفروم",
    calories: 146,
    protein: 28,
    carbs: 0,
    fats: 3.1,
    baseUnit: "100g",
  },
  {
    nameEn: "Turkey Breast",
    nameAr: "صدر ديك رومي",
    calories: 135,
    protein: 30,
    carbs: 0,
    fats: 1,
    baseUnit: "100g",
  },
  {
    nameEn: "Ground Turkey",
    nameAr: "ديك رومي مفروم",
    calories: 189,
    protein: 22,
    carbs: 0,
    fats: 11,
    baseUnit: "100g",
  },
  {
    nameEn: "Lean Beef (Cooked)",
    nameAr: "لحم بقري أحمر (خالي من الدهن)",
    calories: 250,
    protein: 26,
    carbs: 0,
    fats: 15,
    baseUnit: "100g",
  },
  {
    nameEn: "Lean Beef Steak",
    nameAr: "ستيك لحم بقري قليل الدسم",
    calories: 271,
    protein: 27,
    carbs: 0,
    fats: 17.5,
    baseUnit: "100g",
  },
  {
    nameEn: "Ground Beef (Lean)",
    nameAr: "لحم مفروم (قليل الدسم)",
    calories: 212,
    protein: 25,
    carbs: 0,
    fats: 12,
    baseUnit: "100g",
  },
  {
    nameEn: "Beef Liver",
    nameAr: "كبدة بقري",
    calories: 165,
    protein: 26,
    carbs: 3.8,
    fats: 4.4,
    baseUnit: "100g",
  },
  {
    nameEn: "Beef Kidney",
    nameAr: "كلاوي بقري",
    calories: 83,
    protein: 15,
    carbs: 0.4,
    fats: 2.5,
    baseUnit: "100g",
  },
  {
    nameEn: "Lamb (Lean)",
    nameAr: "لحم ضأن (قليل الدسم)",
    calories: 265,
    protein: 25,
    carbs: 0,
    fats: 18,
    baseUnit: "100g",
  },
  {
    nameEn: "Ground Lamb",
    nameAr: "لحم ضأن مفروم",
    calories: 317,
    protein: 21,
    carbs: 0,
    fats: 25,
    baseUnit: "100g",
  },
  {
    nameEn: "Duck Breast",
    nameAr: "صدر بطة",
    calories: 337,
    protein: 19,
    carbs: 0,
    fats: 29,
    baseUnit: "100g",
  },
  {
    nameEn: "Rabbit",
    nameAr: "لحم أرنب",
    calories: 173,
    protein: 21,
    carbs: 0,
    fats: 9,
    baseUnit: "100g",
  },
  {
    nameEn: "Veal",
    nameAr: "لحم عجل",
    calories: 165,
    protein: 31,
    carbs: 0,
    fats: 3.6,
    baseUnit: "100g",
  },

  // === البروتينات (الأسماك) ===
  {
    nameEn: "Tilapia Fish",
    nameAr: "سمك بلطي",
    calories: 96,
    protein: 20,
    carbs: 0,
    fats: 1.7,
    baseUnit: "100g",
  },
  {
    nameEn: "Salmon (Fresh)",
    nameAr: "سمك سلمون (طازج)",
    calories: 208,
    protein: 22,
    carbs: 0,
    fats: 12,
    baseUnit: "100g",
  },
  {
    nameEn: "Salmon (Grilled)",
    nameAr: "سمك سلمون (مشوي)",
    calories: 200,
    protein: 25,
    carbs: 0,
    fats: 11,
    baseUnit: "100g",
  },
  {
    nameEn: "Tuna (in water)",
    nameAr: "تونة (مصفاة من الماء)",
    calories: 96,
    protein: 21,
    carbs: 0,
    fats: 1,
    baseUnit: "100g",
  },
  {
    nameEn: "Tuna (in oil)",
    nameAr: "تونة (بالزيت)",
    calories: 186,
    protein: 19,
    carbs: 0,
    fats: 11,
    baseUnit: "100g",
  },
  {
    nameEn: "Tuna Fresh",
    nameAr: "تونة طازجة (مطهية)",
    calories: 144,
    protein: 29,
    carbs: 0,
    fats: 1.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Cod Fish",
    nameAr: "سمك القد",
    calories: 82,
    protein: 18,
    carbs: 0,
    fats: 0.7,
    baseUnit: "100g",
  },
  {
    nameEn: "Haddock",
    nameAr: "سمك الحد",
    calories: 73,
    protein: 17,
    carbs: 0,
    fats: 0.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Sardines (in oil)",
    nameAr: "سردين (بالزيت)",
    calories: 208,
    protein: 25,
    carbs: 0,
    fats: 11,
    baseUnit: "100g",
  },
  {
    nameEn: "Sardines (in water)",
    nameAr: "سردين (بالماء)",
    calories: 135,
    protein: 25,
    carbs: 0,
    fats: 3.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Herring",
    nameAr: "سمك الرنجة",
    calories: 158,
    protein: 18,
    carbs: 0,
    fats: 9,
    baseUnit: "100g",
  },
  {
    nameEn: "Trout (Rainbow)",
    nameAr: "سمك التراوت",
    calories: 148,
    protein: 20,
    carbs: 0,
    fats: 7,
    baseUnit: "100g",
  },
  {
    nameEn: "Shrimp (Cooked)",
    nameAr: "جمبري (مطهي)",
    calories: 99,
    protein: 24,
    carbs: 0.2,
    fats: 0.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Shrimp (Raw)",
    nameAr: "جمبري (خام)",
    calories: 90,
    protein: 21,
    carbs: 0.2,
    fats: 0.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Squid (Cooked)",
    nameAr: "حبار (مطهي)",
    calories: 92,
    protein: 16,
    carbs: 3.1,
    fats: 1.4,
    baseUnit: "100g",
  },
  {
    nameEn: "Octopus",
    nameAr: "أخطبوط",
    calories: 81,
    protein: 15,
    carbs: 2.2,
    fats: 1,
    baseUnit: "100g",
  },
  {
    nameEn: "Mackerel",
    nameAr: "سمك ماكريل",
    calories: 205,
    protein: 19,
    carbs: 0,
    fats: 14,
    baseUnit: "100g",
  },
  {
    nameEn: "Anchovies",
    nameAr: "سمك الأنشوجة",
    calories: 210,
    protein: 29,
    carbs: 0,
    fats: 10,
    baseUnit: "100g",
  },

  // === البروتينات (البيض ومنتجات الألبان) ===
  {
    nameEn: "Whole Egg",
    nameAr: "بيضة كاملة (مسلوقة)",
    calories: 70,
    protein: 6.3,
    carbs: 0.6,
    fats: 4.8,
    baseUnit: "1 egg",
  },
  {
    nameEn: "Egg White",
    nameAr: "بياض بيض",
    calories: 17,
    protein: 3.6,
    carbs: 0.2,
    fats: 0.1,
    baseUnit: "1 egg white",
  },
  {
    nameEn: "Egg Yolk",
    nameAr: "صفار البيض",
    calories: 55,
    protein: 2.7,
    carbs: 0.6,
    fats: 4.7,
    baseUnit: "1 egg yolk",
  },
  {
    nameEn: "Cottage Cheese (Low Fat)",
    nameAr: "جبنة قريش (قليلة الدسم)",
    calories: 72,
    protein: 13,
    carbs: 2.8,
    fats: 1,
    baseUnit: "100g",
  },
  {
    nameEn: "Cottage Cheese",
    nameAr: "جبنة قريش",
    calories: 98,
    protein: 11,
    carbs: 3.8,
    fats: 4.7,
    baseUnit: "100g",
  },
  {
    nameEn: "Greek Yogurt (0%)",
    nameAr: "زبادي يوناني (خالي الدسم)",
    calories: 40,
    protein: 10,
    carbs: 2,
    fats: 0,
    baseUnit: "100g",
  },
  {
    nameEn: "Greek Yogurt",
    nameAr: "زبادي يوناني (سادة)",
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fats: 0.4,
    baseUnit: "100g",
  },
  {
    nameEn: "Skyr Yogurt",
    nameAr: "زبادي سكير",
    calories: 61,
    protein: 11,
    carbs: 4,
    fats: 0.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Normal Yogurt",
    nameAr: "زبادي بلدي",
    calories: 61,
    protein: 3.5,
    carbs: 4.7,
    fats: 3.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Skimmed Milk",
    nameAr: "حليب خالي الدسم",
    calories: 34,
    protein: 3.4,
    carbs: 5,
    fats: 0.1,
    baseUnit: "100ml",
  },
  {
    nameEn: "Semi-Skimmed Milk",
    nameAr: "حليب نصف دسم",
    calories: 49,
    protein: 3.3,
    carbs: 4.8,
    fats: 1.6,
    baseUnit: "100ml",
  },
  {
    nameEn: "Full Fat Milk",
    nameAr: "حليب كامل الدسم",
    calories: 61,
    protein: 3.2,
    carbs: 4.8,
    fats: 3.3,
    baseUnit: "100ml",
  },
  {
    nameEn: "Goat Cheese",
    nameAr: "جبنة الماعز",
    calories: 364,
    protein: 21,
    carbs: 0.9,
    fats: 30,
    baseUnit: "100g",
  },
  {
    nameEn: "Feta Cheese",
    nameAr: "جبنة الفيتا",
    calories: 265,
    protein: 14,
    carbs: 4.1,
    fats: 21,
    baseUnit: "100g",
  },
  {
    nameEn: "Cheddar Cheese",
    nameAr: "جبنة تشيدر",
    calories: 402,
    protein: 23,
    carbs: 3.6,
    fats: 33,
    baseUnit: "100g",
  },
  {
    nameEn: "Mozzarella Cheese",
    nameAr: "جبنة موتزاريلا",
    calories: 280,
    protein: 28,
    carbs: 3.1,
    fats: 17,
    baseUnit: "100g",
  },
  {
    nameEn: "Ricotta Cheese",
    nameAr: "جبنة ريكوتا",
    calories: 174,
    protein: 11,
    carbs: 3.6,
    fats: 13,
    baseUnit: "100g",
  },
  {
    nameEn: "Cream Cheese",
    nameAr: "جبنة كريمية",
    calories: 342,
    protein: 5.9,
    carbs: 4.1,
    fats: 34,
    baseUnit: "100g",
  },

  // === النشويات (الكربوهيدرات) ===
  {
    nameEn: "Rolled Oats",
    nameAr: "شوفان (خام)",
    calories: 389,
    protein: 16.9,
    carbs: 66,
    fats: 6.9,
    baseUnit: "100g",
  },
  {
    nameEn: "Oatmeal (Cooked)",
    nameAr: "دقيق الشوفان (مطبوخ)",
    calories: 68,
    protein: 2.4,
    carbs: 12,
    fats: 1.4,
    baseUnit: "100g",
  },
  {
    nameEn: "Steel Cut Oats",
    nameAr: "شوفان مقطع",
    calories: 380,
    protein: 17,
    carbs: 65,
    fats: 7,
    baseUnit: "100g",
  },
  {
    nameEn: "Instant Oats",
    nameAr: "شوفان فوري",
    calories: 389,
    protein: 16.4,
    carbs: 66,
    fats: 6.9,
    baseUnit: "100g",
  },
  {
    nameEn: "White Rice (Cooked)",
    nameAr: "أرز أبيض (مطبوخ)",
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fats: 0.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Basmati Rice (Cooked)",
    nameAr: "أرز بسمتي (مطبوخ)",
    calories: 121,
    protein: 3.5,
    carbs: 25,
    fats: 0.4,
    baseUnit: "100g",
  },
  {
    nameEn: "Brown Rice (Cooked)",
    nameAr: "أرز بني (مطبوخ)",
    calories: 111,
    protein: 2.6,
    carbs: 23,
    fats: 0.9,
    baseUnit: "100g",
  },
  {
    nameEn: "Jasmine Rice (Cooked)",
    nameAr: "أرز ياسمين (مطبوخ)",
    calories: 130,
    protein: 2.7,
    carbs: 28.2,
    fats: 0.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Arborio Rice",
    nameAr: "أرز أربوريو",
    calories: 131,
    protein: 3,
    carbs: 29,
    fats: 0.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Wild Rice",
    nameAr: "أرز بري",
    calories: 101,
    protein: 3.9,
    carbs: 35,
    fats: 0.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Spaghetti (Cooked)",
    nameAr: "سباجيتي (مطبوخة)",
    calories: 158,
    protein: 5.8,
    carbs: 31,
    fats: 1,
    baseUnit: "100g",
  },
  {
    nameEn: "Pasta (Cooked)",
    nameAr: "مكرونة (مطبوخة)",
    calories: 158,
    protein: 5.8,
    carbs: 31,
    fats: 1,
    baseUnit: "100g",
  },
  {
    nameEn: "Whole Wheat Pasta (Cooked)",
    nameAr: "مكرونة قمح كامل (مطبوخة)",
    calories: 124,
    protein: 6,
    carbs: 26,
    fats: 0.9,
    baseUnit: "100g",
  },
  {
    nameEn: "Sweet Potato (Cooked)",
    nameAr: "بطاطا حلوة (مشوية/مسلوقة)",
    calories: 86,
    protein: 1.6,
    carbs: 20,
    fats: 0.1,
    baseUnit: "100g",
  },
  {
    nameEn: "Sweet Potato (Baked)",
    nameAr: "بطاطا حلوة (مخبوزة)",
    calories: 103,
    protein: 2,
    carbs: 24,
    fats: 0.1,
    baseUnit: "100g",
  },
  {
    nameEn: "Potato (Boiled)",
    nameAr: "بطاطس (مسلوقة)",
    calories: 77,
    protein: 2,
    carbs: 17,
    fats: 0.1,
    baseUnit: "100g",
  },
  {
    nameEn: "Potato (Baked)",
    nameAr: "بطاطس (مخبوزة)",
    calories: 93,
    protein: 2.1,
    carbs: 21,
    fats: 0.1,
    baseUnit: "100g",
  },
  {
    nameEn: "Potato (Fried)",
    nameAr: "بطاطس (مقلية)",
    calories: 365,
    protein: 3.4,
    carbs: 41,
    fats: 20,
    baseUnit: "100g",
  },
  {
    nameEn: "Yam",
    nameAr: "اليام (بطاطا يابانية)",
    calories: 101,
    protein: 1.5,
    carbs: 24,
    fats: 0.2,
    baseUnit: "100g",
  },
  {
    nameEn: "Cassava Root",
    nameAr: "جذر الكسافا",
    calories: 160,
    protein: 1.4,
    carbs: 38,
    fats: 0.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Baladi Bread",
    nameAr: "عيش بلدي (مصري)",
    calories: 275,
    protein: 9,
    carbs: 55,
    fats: 1,
    baseUnit: "100g",
  },
  {
    nameEn: "Whole Wheat Bread",
    nameAr: "عيش سن (قمح كامل)",
    calories: 247,
    protein: 13,
    carbs: 43,
    fats: 3.5,
    baseUnit: "100g",
  },
  {
    nameEn: "White Bread",
    nameAr: "عيش أبيض",
    calories: 265,
    protein: 9.2,
    carbs: 49,
    fats: 3.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Rye Bread",
    nameAr: "خبز الجاودار",
    calories: 259,
    protein: 10,
    carbs: 48,
    fats: 3.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Sourdough Bread",
    nameAr: "خبز الخميرة الطبيعية",
    calories: 289,
    protein: 9.2,
    carbs: 51,
    fats: 4.5,
    baseUnit: "100g",
  },
  {
    nameEn: "Pita Bread",
    nameAr: "خبز البيتا",
    calories: 275,
    protein: 9,
    carbs: 55,
    fats: 1.1,
    baseUnit: "100g",
  },
  {
    nameEn: "Naan Bread",
    nameAr: "خبز النان",
    calories: 300,
    protein: 10,
    carbs: 51,
    fats: 8,
    baseUnit: "100g",
  },
  {
    nameEn: "Bagel",
    nameAr: "الباجل",
    calories: 245,
    protein: 9,
    carbs: 48,
    fats: 1.5,
    baseUnit: "1 bagel",
  },
  {
    nameEn: "Rice Cakes",
    nameAr: "رايس كيك (قطعة)",
    calories: 35,
    protein: 0.7,
    carbs: 7.3,
    fats: 0.3,
    baseUnit: "1 piece",
  },
  {
    nameEn: "Polenta (Cooked)",
    nameAr: "بولنتا (مطبوخة)",
    calories: 68,
    protein: 1.5,
    carbs: 14,
    fats: 0.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Couscous (Cooked)",
    nameAr: "كسكسي (مطبوخ)",
    calories: 112,
    protein: 3.8,
    carbs: 23,
    fats: 0.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Quinoa (Cooked)",
    nameAr: "الكينوا (مطبوخة)",
    calories: 120,
    protein: 4.4,
    carbs: 21,
    fats: 2.4,
    baseUnit: "100g",
  },
  {
    nameEn: "Buckwheat (Cooked)",
    nameAr: "الحنطة السوداء (مطبوخة)",
    calories: 155,
    protein: 5.4,
    carbs: 33,
    fats: 1,
    baseUnit: "100g",
  },
  {
    nameEn: "Millet (Cooked)",
    nameAr: "الدخن (مطبوخ)",
    calories: 119,
    protein: 3.5,
    carbs: 23,
    fats: 1,
    baseUnit: "100g",
  },

  // === البقوليات ===
  {
    nameEn: "Fava Beans (Cooked)",
    nameAr: "فول مدمس",
    calories: 110,
    protein: 8,
    carbs: 20,
    fats: 1,
    baseUnit: "100g",
  },
  {
    nameEn: "Fava Beans (Canned)",
    nameAr: "فول معلب",
    calories: 88,
    protein: 6,
    carbs: 16,
    fats: 0.5,
    baseUnit: "100g",
  },
  {
    nameEn: "Green Beans (Cooked)",
    nameAr: "فاصوليا خضراء (مطبوخة)",
    calories: 30,
    protein: 2.2,
    carbs: 7,
    fats: 0.2,
    baseUnit: "100g",
  },
  {
    nameEn: "Lentils (Cooked)",
    nameAr: "عدس أصفر (مطبوخ)",
    calories: 116,
    protein: 9,
    carbs: 20,
    fats: 0.4,
    baseUnit: "100g",
  },
  {
    nameEn: "Red Lentils (Cooked)",
    nameAr: "عدس أحمر (مطبوخ)",
    calories: 116,
    protein: 9.1,
    carbs: 20,
    fats: 0.4,
    baseUnit: "100g",
  },
  {
    nameEn: "Green Lentils (Cooked)",
    nameAr: "عدس أخضر (مطبوخ)",
    calories: 115,
    protein: 9.1,
    carbs: 20,
    fats: 0.4,
    baseUnit: "100g",
  },
  {
    nameEn: "Black Lentils (Cooked)",
    nameAr: "عدس أسود (مطبوخ)",
    calories: 115,
    protein: 9.2,
    carbs: 20,
    fats: 0.4,
    baseUnit: "100g",
  },
  {
    nameEn: "Chickpeas (Cooked)",
    nameAr: "حمص الشام (مطبوخ)",
    calories: 164,
    protein: 9,
    carbs: 27,
    fats: 2.6,
    baseUnit: "100g",
  },
  {
    nameEn: "Chickpeas (Canned)",
    nameAr: "حمص معلب",
    calories: 134,
    protein: 7.3,
    carbs: 22,
    fats: 2.1,
    baseUnit: "100g",
  },
  {
    nameEn: "Kidney Beans (Cooked)",
    nameAr: "فاصوليا حمراء (مطبوخة)",
    calories: 127,
    protein: 8.7,
    carbs: 23,
    fats: 0.4,
    baseUnit: "100g",
  },
  {
    nameEn: "Black Beans (Cooked)",
    nameAr: "فاصوليا سوداء (مطبوخة)",
    calories: 132,
    protein: 8.7,
    carbs: 24,
    fats: 0.5,
    baseUnit: "100g",
  },
  {
    nameEn: "Pinto Beans (Cooked)",
    nameAr: "فاصوليا بينتو (مطبوخة)",
    calories: 143,
    protein: 8.9,
    carbs: 26,
    fats: 0.6,
    baseUnit: "100g",
  },
  {
    nameEn: "Navy Beans (Cooked)",
    nameAr: "فاصوليا بيضاء صغيرة",
    calories: 150,
    protein: 8.8,
    carbs: 27,
    fats: 0.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Peas (Cooked)",
    nameAr: "بازلاء (مطبوخة)",
    calories: 84,
    protein: 5.4,
    carbs: 15,
    fats: 0.2,
    baseUnit: "100g",
  },
  {
    nameEn: "Split Peas (Cooked)",
    nameAr: "بازلاء مقسومة (مطبوخة)",
    calories: 134,
    protein: 8.2,
    carbs: 24,
    fats: 0.4,
    baseUnit: "100g",
  },
  {
    nameEn: "Soy Beans (Cooked)",
    nameAr: "فول الصويا (مطبوخ)",
    calories: 172,
    protein: 18,
    carbs: 10,
    fats: 9,
    baseUnit: "100g",
  },

  // === الدهون الصحية ===
  {
    nameEn: "Olive Oil",
    nameAr: "زيت زيتون",
    calories: 119,
    protein: 0,
    carbs: 0,
    fats: 13.5,
    baseUnit: "1 tbsp (15ml)",
  },
  {
    nameEn: "Coconut Oil",
    nameAr: "زيت جوز الهند",
    calories: 117,
    protein: 0,
    carbs: 0,
    fats: 13.5,
    baseUnit: "1 tbsp (14g)",
  },
  {
    nameEn: "Sesame Oil",
    nameAr: "زيت السمسم",
    calories: 120,
    protein: 0,
    carbs: 0,
    fats: 13.6,
    baseUnit: "1 tbsp (15ml)",
  },
  {
    nameEn: "Sunflower Oil",
    nameAr: "زيت دوار الشمس",
    calories: 120,
    protein: 0,
    carbs: 0,
    fats: 13.6,
    baseUnit: "1 tbsp (14g)",
  },
  {
    nameEn: "Almond Oil",
    nameAr: "زيت اللوز",
    calories: 120,
    protein: 0,
    carbs: 0,
    fats: 13.6,
    baseUnit: "1 tbsp (14g)",
  },
  {
    nameEn: "Avocado Oil",
    nameAr: "زيت الأفوكادو",
    calories: 120,
    protein: 0,
    carbs: 0,
    fats: 13.6,
    baseUnit: "1 tbsp (14g)",
  },
  {
    nameEn: "Peanut Oil",
    nameAr: "زيت الفول السوداني",
    calories: 119,
    protein: 0,
    carbs: 0,
    fats: 13.5,
    baseUnit: "1 tbsp (14g)",
  },
  {
    nameEn: "Butter",
    nameAr: "الزبدة",
    calories: 102,
    protein: 0.1,
    carbs: 0,
    fats: 11.5,
    baseUnit: "1 tbsp (14g)",
  },
  {
    nameEn: "Ghee (Clarified Butter)",
    nameAr: "السمن (زبدة مصفاة)",
    calories: 112,
    protein: 0,
    carbs: 0,
    fats: 12.7,
    baseUnit: "1 tbsp (15ml)",
  },
  {
    nameEn: "Peanut Butter",
    nameAr: "زبدة فول سوداني",
    calories: 94,
    protein: 4,
    carbs: 3,
    fats: 8,
    baseUnit: "1 tbsp (16g)",
  },
  {
    nameEn: "Almond Butter",
    nameAr: "زبدة اللوز",
    calories: 98,
    protein: 3.4,
    carbs: 3.4,
    fats: 9.5,
    baseUnit: "1 tbsp (16g)",
  },
  {
    nameEn: "Cashew Butter",
    nameAr: "زبدة الكاجو",
    calories: 94,
    protein: 3.1,
    carbs: 4.6,
    fats: 8.1,
    baseUnit: "1 tbsp (16g)",
  },
  {
    nameEn: "Sunflower Seed Butter",
    nameAr: "زبدة بذور عباد الشمس",
    calories: 95,
    protein: 3.7,
    carbs: 4.4,
    fats: 8.1,
    baseUnit: "1 tbsp (16g)",
  },
  {
    nameEn: "Tahini",
    nameAr: "الطحينة (معجون السمسم)",
    calories: 89,
    protein: 3,
    carbs: 3.5,
    fats: 8.1,
    baseUnit: "1 tbsp (15g)",
  },
  {
    nameEn: "Almonds",
    nameAr: "لوز (خام)",
    calories: 579,
    protein: 21,
    carbs: 22,
    fats: 50,
    baseUnit: "100g",
  },
  {
    nameEn: "Almonds (Roasted)",
    nameAr: "لوز (محمص)",
    calories: 585,
    protein: 21,
    carbs: 20,
    fats: 51,
    baseUnit: "100g",
  },
  {
    nameEn: "Peanuts",
    nameAr: "فول سوداني (محمص)",
    calories: 567,
    protein: 26,
    carbs: 16,
    fats: 49,
    baseUnit: "100g",
  },
  {
    nameEn: "Peanuts (Raw)",
    nameAr: "فول سوداني (خام)",
    calories: 567,
    protein: 26,
    carbs: 16,
    fats: 49,
    baseUnit: "100g",
  },
  {
    nameEn: "Walnuts",
    nameAr: "عين جمل",
    calories: 654,
    protein: 15,
    carbs: 14,
    fats: 65,
    baseUnit: "100g",
  },
  {
    nameEn: "Cashews",
    nameAr: "الكاجو",
    calories: 553,
    protein: 18,
    carbs: 30,
    fats: 44,
    baseUnit: "100g",
  },
  {
    nameEn: "Brazil Nuts",
    nameAr: "جوز البرازيل",
    calories: 656,
    protein: 14,
    carbs: 12,
    fats: 66,
    baseUnit: "100g",
  },
  {
    nameEn: "Pistachios",
    nameAr: "الفستق الحلبي",
    calories: 562,
    protein: 20,
    carbs: 28,
    fats: 45,
    baseUnit: "100g",
  },
  {
    nameEn: "Hazelnuts",
    nameAr: "بندق",
    calories: 628,
    protein: 15,
    carbs: 17,
    fats: 61,
    baseUnit: "100g",
  },
  {
    nameEn: "Macadamia Nuts",
    nameAr: "جوز المكاديميا",
    calories: 718,
    protein: 8,
    carbs: 14,
    fats: 76,
    baseUnit: "100g",
  },
  {
    nameEn: "Pine Nuts",
    nameAr: "صنوبر",
    calories: 673,
    protein: 14,
    carbs: 13,
    fats: 68,
    baseUnit: "100g",
  },
  {
    nameEn: "Sunflower Seeds",
    nameAr: "بذور عباد الشمس",
    calories: 585,
    protein: 21,
    carbs: 20,
    fats: 51,
    baseUnit: "100g",
  },
  {
    nameEn: "Pumpkin Seeds",
    nameAr: "بذور اليقطين",
    calories: 541,
    protein: 25,
    carbs: 5,
    fats: 49,
    baseUnit: "100g",
  },
  {
    nameEn: "Sesame Seeds",
    nameAr: "بذور السمسم",
    calories: 563,
    protein: 17,
    carbs: 23,
    fats: 50,
    baseUnit: "100g",
  },
  {
    nameEn: "Chia Seeds",
    nameAr: "بذور الشيا",
    calories: 486,
    protein: 17,
    carbs: 42,
    fats: 31,
    baseUnit: "100g",
  },
  {
    nameEn: "Flaxseeds",
    nameAr: "بذور الكتان",
    calories: 534,
    protein: 18,
    carbs: 29,
    fats: 42,
    baseUnit: "100g",
  },
  {
    nameEn: "Hemp Seeds",
    nameAr: "بذور القنب",
    calories: 560,
    protein: 32,
    carbs: 12,
    fats: 31,
    baseUnit: "100g",
  },
  {
    nameEn: "Avocado",
    nameAr: "أفوكادو",
    calories: 160,
    protein: 2,
    carbs: 9,
    fats: 15,
    baseUnit: "100g",
  },
  {
    nameEn: "Avocado Oil",
    nameAr: "زيت الأفوكادو",
    calories: 120,
    protein: 0,
    carbs: 0,
    fats: 13.6,
    baseUnit: "1 tbsp (14g)",
  },
  {
    nameEn: "Coconut Milk",
    nameAr: "حليب جوز الهند",
    calories: 230,
    protein: 2.3,
    carbs: 5.5,
    fats: 24,
    baseUnit: "100ml",
  },
  {
    nameEn: "Coconut Meat (Raw)",
    nameAr: "لحم جوز الهند",
    calories: 354,
    protein: 3.3,
    carbs: 15,
    fats: 34,
    baseUnit: "100g",
  },

  // === الفواكه ===
  {
    nameEn: "Banana",
    nameAr: "موز",
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fats: 0.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Plantain",
    nameAr: "موز الطبخ",
    calories: 122,
    protein: 1,
    carbs: 32,
    fats: 0.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Dates",
    nameAr: "تمر",
    calories: 277,
    protein: 1.8,
    carbs: 75,
    fats: 0.2,
    baseUnit: "100g",
  },
  {
    nameEn: "Dried Figs",
    nameAr: "تين مجفف",
    calories: 249,
    protein: 3.3,
    carbs: 63,
    fats: 0.9,
    baseUnit: "100g",
  },
  {
    nameEn: "Dried Raisins",
    nameAr: "زبيب",
    calories: 299,
    protein: 3.1,
    carbs: 79,
    fats: 0.5,
    baseUnit: "100g",
  },
  {
    nameEn: "Dried Apricots",
    nameAr: "مشمش مجفف",
    calories: 241,
    protein: 3.4,
    carbs: 62,
    fats: 0.5,
    baseUnit: "100g",
  },
  {
    nameEn: "Dried Cranberries",
    nameAr: "توت بري مجفف",
    calories: 308,
    protein: 0.4,
    carbs: 82,
    fats: 0.4,
    baseUnit: "100g",
  },
  {
    nameEn: "Dried Prunes",
    nameAr: "تمر هندي مجفف",
    calories: 240,
    protein: 2.2,
    carbs: 64,
    fats: 0.4,
    baseUnit: "100g",
  },
  {
    nameEn: "Apple",
    nameAr: "تفاح",
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fats: 0.2,
    baseUnit: "100g",
  },
  {
    nameEn: "Pear",
    nameAr: "إجاص",
    calories: 57,
    protein: 0.4,
    carbs: 15,
    fats: 0.1,
    baseUnit: "100g",
  },
  {
    nameEn: "Orange",
    nameAr: "برتقال",
    calories: 47,
    protein: 0.9,
    carbs: 12,
    fats: 0.1,
    baseUnit: "100g",
  },
  {
    nameEn: "Mandarin",
    nameAr: "يوسفي",
    calories: 47,
    protein: 0.7,
    carbs: 12,
    fats: 0.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Grapefruit",
    nameAr: "جريب فروت",
    calories: 42,
    protein: 0.8,
    carbs: 11,
    fats: 0.1,
    baseUnit: "100g",
  },
  {
    nameEn: "Lemon",
    nameAr: "ليمون",
    calories: 29,
    protein: 1.1,
    carbs: 9,
    fats: 0.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Lime",
    nameAr: "ليمة",
    calories: 30,
    protein: 0.7,
    carbs: 11,
    fats: 0.2,
    baseUnit: "100g",
  },
  {
    nameEn: "Watermelon",
    nameAr: "بطيخ",
    calories: 30,
    protein: 0.6,
    carbs: 8,
    fats: 0.2,
    baseUnit: "100g",
  },
  {
    nameEn: "Cantaloupe",
    nameAr: "شمام",
    calories: 36,
    protein: 0.8,
    carbs: 9,
    fats: 0.2,
    baseUnit: "100g",
  },
  {
    nameEn: "Honeydew Melon",
    nameAr: "شمام أخضر",
    calories: 36,
    protein: 0.5,
    carbs: 9,
    fats: 0.1,
    baseUnit: "100g",
  },
  {
    nameEn: "Strawberries",
    nameAr: "فراولة",
    calories: 32,
    protein: 0.7,
    carbs: 7.7,
    fats: 0.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Blueberries",
    nameAr: "توت أزرق",
    calories: 57,
    protein: 0.7,
    carbs: 14,
    fats: 0.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Raspberries",
    nameAr: "توت العليق",
    calories: 52,
    protein: 1.2,
    carbs: 12,
    fats: 0.7,
    baseUnit: "100g",
  },
  {
    nameEn: "Blackberries",
    nameAr: "توت أسود",
    calories: 43,
    protein: 1.4,
    carbs: 10,
    fats: 0.5,
    baseUnit: "100g",
  },
  {
    nameEn: "Cranberries",
    nameAr: "توت بري طازج",
    calories: 46,
    protein: 0.4,
    carbs: 12,
    fats: 0.1,
    baseUnit: "100g",
  },
  {
    nameEn: "Kiwi",
    nameAr: "كيوي",
    calories: 61,
    protein: 1.1,
    carbs: 15,
    fats: 0.5,
    baseUnit: "100g",
  },
  {
    nameEn: "Mango",
    nameAr: "مانجو",
    calories: 60,
    protein: 0.8,
    carbs: 15,
    fats: 0.4,
    baseUnit: "100g",
  },
  {
    nameEn: "Papaya",
    nameAr: "ببايا",
    calories: 43,
    protein: 0.6,
    carbs: 11,
    fats: 0.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Pineapple",
    nameAr: "أناناس",
    calories: 50,
    protein: 0.5,
    carbs: 13,
    fats: 0.1,
    baseUnit: "100g",
  },
  {
    nameEn: "Dragon Fruit",
    nameAr: "فاكهة التنين",
    calories: 57,
    protein: 1.2,
    carbs: 13,
    fats: 0.4,
    baseUnit: "100g",
  },
  {
    nameEn: "Passion Fruit",
    nameAr: "ثمرة العاطفة",
    calories: 97,
    protein: 2.2,
    carbs: 23,
    fats: 0.4,
    baseUnit: "100g",
  },
  {
    nameEn: "Guava",
    nameAr: "جوافة",
    calories: 68,
    protein: 2.6,
    carbs: 14,
    fats: 0.9,
    baseUnit: "100g",
  },
  {
    nameEn: "Pomegranate",
    nameAr: "رمان",
    calories: 83,
    protein: 1.7,
    carbs: 19,
    fats: 1.2,
    baseUnit: "100g",
  },
  {
    nameEn: "Cherry",
    nameAr: "كرز",
    calories: 63,
    protein: 1.1,
    carbs: 16,
    fats: 0.2,
    baseUnit: "100g",
  },
  {
    nameEn: "Peach",
    nameAr: "دراق",
    calories: 39,
    protein: 0.9,
    carbs: 10,
    fats: 0.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Plum",
    nameAr: "برقوق",
    calories: 46,
    protein: 0.7,
    carbs: 11,
    fats: 0.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Apricot",
    nameAr: "مشمش طازج",
    calories: 48,
    protein: 1.4,
    carbs: 11,
    fats: 0.4,
    baseUnit: "100g",
  },
  {
    nameEn: "Coconut (Fresh)",
    nameAr: "جوز هند طازج",
    calories: 354,
    protein: 3.3,
    carbs: 15,
    fats: 34,
    baseUnit: "100g",
  },

  // === الخضروات ===
  {
    nameEn: "Broccoli (Raw)",
    nameAr: "بروكلي (خام)",
    calories: 34,
    protein: 2.8,
    carbs: 6,
    fats: 0.4,
    baseUnit: "100g",
  },
  {
    nameEn: "Broccoli (Cooked)",
    nameAr: "بروكلي (مطبوخ)",
    calories: 30,
    protein: 2.6,
    carbs: 5.5,
    fats: 0.4,
    baseUnit: "100g",
  },
  {
    nameEn: "Cauliflower (Raw)",
    nameAr: "قرنبيط (خام)",
    calories: 25,
    protein: 1.9,
    carbs: 5,
    fats: 0.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Cauliflower (Cooked)",
    nameAr: "قرنبيط (مطبوخ)",
    calories: 23,
    protein: 1.9,
    carbs: 4,
    fats: 0.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Cabbage (Raw)",
    nameAr: "ملفوف (خام)",
    calories: 25,
    protein: 1.3,
    carbs: 6,
    fats: 0.1,
    baseUnit: "100g",
  },
  {
    nameEn: "Spinach (Raw)",
    nameAr: "سبانخ (خام)",
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fats: 0.4,
    baseUnit: "100g",
  },
  {
    nameEn: "Spinach (Cooked)",
    nameAr: "سبانخ (مطبوخة)",
    calories: 23,
    protein: 3,
    carbs: 3.6,
    fats: 0.4,
    baseUnit: "100g",
  },
  {
    nameEn: "Kale",
    nameAr: "كايل",
    calories: 49,
    protein: 4.3,
    carbs: 9,
    fats: 0.9,
    baseUnit: "100g",
  },
  {
    nameEn: "Arugula",
    nameAr: "جرجير",
    calories: 25,
    protein: 2.6,
    carbs: 3.7,
    fats: 0.7,
    baseUnit: "100g",
  },
  {
    nameEn: "Swiss Chard",
    nameAr: "السلق السويسري",
    calories: 19,
    protein: 1.8,
    carbs: 3.7,
    fats: 0.2,
    baseUnit: "100g",
  },
  {
    nameEn: "Cucumber (Raw)",
    nameAr: "خيار (خام)",
    calories: 15,
    protein: 0.7,
    carbs: 3.6,
    fats: 0.1,
    baseUnit: "100g",
  },
  {
    nameEn: "Tomato (Raw)",
    nameAr: "طماطم (خام)",
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fats: 0.2,
    baseUnit: "100g",
  },
  {
    nameEn: "Tomato (Cooked)",
    nameAr: "طماطم (مطبوخة)",
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fats: 0.2,
    baseUnit: "100g",
  },
  {
    nameEn: "Cherry Tomato",
    nameAr: "طماطم كرز",
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fats: 0.2,
    baseUnit: "100g",
  },
  {
    nameEn: "Bell Pepper (Red)",
    nameAr: "فلفل أحمر (حلو)",
    calories: 31,
    protein: 1,
    carbs: 6,
    fats: 0.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Bell Pepper (Green)",
    nameAr: "فلفل أخضر (حلو)",
    calories: 30,
    protein: 1,
    carbs: 7,
    fats: 0.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Bell Pepper (Yellow)",
    nameAr: "فلفل أصفر (حلو)",
    calories: 30,
    protein: 1,
    carbs: 7,
    fats: 0.2,
    baseUnit: "100g",
  },
  {
    nameEn: "Chili Pepper",
    nameAr: "فلفل حار",
    calories: 40,
    protein: 2,
    carbs: 9,
    fats: 0.4,
    baseUnit: "100g",
  },
  {
    nameEn: "Zucchini",
    nameAr: "كوسة",
    calories: 17,
    protein: 1.5,
    carbs: 3.5,
    fats: 0.4,
    baseUnit: "100g",
  },
  {
    nameEn: "Eggplant",
    nameAr: "باذنجان",
    calories: 25,
    protein: 1,
    carbs: 6,
    fats: 0.2,
    baseUnit: "100g",
  },
  {
    nameEn: "Asparagus",
    nameAr: "هليون",
    calories: 20,
    protein: 2.2,
    carbs: 3.7,
    fats: 0.1,
    baseUnit: "100g",
  },
  {
    nameEn: "Green Beans",
    nameAr: "فاصوليا خضراء",
    calories: 30,
    protein: 2.2,
    carbs: 7,
    fats: 0.2,
    baseUnit: "100g",
  },
  {
    nameEn: "Peas",
    nameAr: "بازلاء",
    calories: 84,
    protein: 5.4,
    carbs: 15,
    fats: 0.2,
    baseUnit: "100g",
  },
  {
    nameEn: "Corn",
    nameAr: "ذرة",
    calories: 86,
    protein: 3.3,
    carbs: 19,
    fats: 1.2,
    baseUnit: "100g",
  },
  {
    nameEn: "Carrots (Raw)",
    nameAr: "جزر (خام)",
    calories: 41,
    protein: 0.9,
    carbs: 10,
    fats: 0.2,
    baseUnit: "100g",
  },
  {
    nameEn: "Carrots (Cooked)",
    nameAr: "جزر (مطبوخ)",
    calories: 35,
    protein: 0.7,
    carbs: 8,
    fats: 0.2,
    baseUnit: "100g",
  },
  {
    nameEn: "Beets",
    nameAr: "شمندر",
    calories: 43,
    protein: 1.6,
    carbs: 10,
    fats: 0.2,
    baseUnit: "100g",
  },
  {
    nameEn: "Turnip",
    nameAr: "اللفت",
    calories: 36,
    protein: 1.1,
    carbs: 8,
    fats: 0.1,
    baseUnit: "100g",
  },
  {
    nameEn: "Radish",
    nameAr: "فجل",
    calories: 16,
    protein: 0.7,
    carbs: 3.4,
    fats: 0.1,
    baseUnit: "100g",
  },
  {
    nameEn: "Celery",
    nameAr: "كرفس",
    calories: 16,
    protein: 0.7,
    carbs: 3.7,
    fats: 0.2,
    baseUnit: "100g",
  },
  {
    nameEn: "Lettuce (Romaine)",
    nameAr: "خس روماني",
    calories: 15,
    protein: 1.2,
    carbs: 3,
    fats: 0.2,
    baseUnit: "100g",
  },
  {
    nameEn: "Lettuce (Iceberg)",
    nameAr: "خس جليدي",
    calories: 14,
    protein: 0.9,
    carbs: 2.9,
    fats: 0.1,
    baseUnit: "100g",
  },
  {
    nameEn: "Mixed Greens",
    nameAr: "خضار مختلطة",
    calories: 15,
    protein: 1,
    carbs: 3,
    fats: 0.2,
    baseUnit: "100g",
  },
  {
    nameEn: "Onion",
    nameAr: "بصل",
    calories: 40,
    protein: 1.1,
    carbs: 9,
    fats: 0.1,
    baseUnit: "100g",
  },
  {
    nameEn: "Garlic",
    nameAr: "ثوم",
    calories: 149,
    protein: 6.4,
    carbs: 33,
    fats: 0.5,
    baseUnit: "100g",
  },
  {
    nameEn: "Mushrooms",
    nameAr: "فطر",
    calories: 22,
    protein: 3.1,
    carbs: 3.3,
    fats: 0.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Mushrooms (Cooked)",
    nameAr: "فطر (مطبوخ)",
    calories: 22,
    protein: 3.5,
    carbs: 3.3,
    fats: 0.3,
    baseUnit: "100g",
  },
  {
    nameEn: "Artichoke",
    nameAr: "أرضي شوكي",
    calories: 47,
    protein: 3.3,
    carbs: 10,
    fats: 0.2,
    baseUnit: "100g",
  },
  {
    nameEn: "Brussels Sprouts",
    nameAr: "كرنب بروكسل",
    calories: 43,
    protein: 3.4,
    carbs: 8,
    fats: 0.4,
    baseUnit: "100g",
  },
  {
    nameEn: "Okra",
    nameAr: "باميا",
    calories: 33,
    protein: 1.9,
    carbs: 7,
    fats: 0.2,
    baseUnit: "100g",
  },
  {
    nameEn: "Kohlrabi",
    nameAr: "كرنب أرضي",
    calories: 27,
    protein: 1.7,
    carbs: 6,
    fats: 0.1,
    baseUnit: "100g",
  },

  // === المكملات الغذائية ===
  {
    nameEn: "Whey Protein Isolate",
    nameAr: "واي بروتين ايزوليت",
    calories: 110,
    protein: 25,
    carbs: 1,
    fats: 0,
    baseUnit: "1 scoop (30g)",
  },
  {
    nameEn: "Whey Protein Concentrate",
    nameAr: "واي بروتين كونسينتريت",
    calories: 120,
    protein: 24,
    carbs: 3,
    fats: 2,
    baseUnit: "1 scoop (30g)",
  },
  {
    nameEn: "Whey Protein Blend",
    nameAr: "واي بروتين مزيج",
    calories: 115,
    protein: 24,
    carbs: 2,
    fats: 1,
    baseUnit: "1 scoop (30g)",
  },
  {
    nameEn: "Casein Protein",
    nameAr: "بروتين كازين (بطيء الامتصاص)",
    calories: 110,
    protein: 24,
    carbs: 3,
    fats: 1,
    baseUnit: "1 scoop (30g)",
  },
  {
    nameEn: "Egg Protein Powder",
    nameAr: "بروتين البيض",
    calories: 100,
    protein: 23,
    carbs: 0.5,
    fats: 0.5,
    baseUnit: "1 scoop (30g)",
  },
  {
    nameEn: "Plant-Based Protein",
    nameAr: "بروتين نباتي",
    calories: 130,
    protein: 22,
    carbs: 5,
    fats: 2,
    baseUnit: "1 scoop (30g)",
  },
  {
    nameEn: "Hemp Protein",
    nameAr: "بروتين القنب",
    calories: 162,
    protein: 12,
    carbs: 2.3,
    fats: 12,
    baseUnit: "100g",
  },
  {
    nameEn: "Pea Protein",
    nameAr: "بروتين البازلاء",
    calories: 120,
    protein: 24,
    carbs: 2,
    fats: 2,
    baseUnit: "1 scoop (30g)",
  },
  {
    nameEn: "Mass Gainer",
    nameAr: "ماس جينر",
    calories: 350,
    protein: 15,
    carbs: 70,
    fats: 3,
    baseUnit: "1 scoop",
  },
  {
    nameEn: "Weight Gainer (Low Fat)",
    nameAr: "جينر قليل الدسم",
    calories: 300,
    protein: 20,
    carbs: 60,
    fats: 2,
    baseUnit: "1 scoop",
  },
  {
    nameEn: "Creatine Monohydrate",
    nameAr: "كرياتين أحادي الهيدرات",
    calories: 0,
    protein: 0,
    carbs: 0,
    fats: 0,
    baseUnit: "1 scoop (5g)",
  },
  {
    nameEn: "BCAAs (Branched-Chain Amino Acids)",
    nameAr: "أحماض أمينية متفرعة",
    calories: 20,
    protein: 5,
    carbs: 0,
    fats: 0,
    baseUnit: "1 scoop (5g)",
  },
  {
    nameEn: "Glutamine",
    nameAr: "الجلوتامين",
    calories: 20,
    protein: 5,
    carbs: 0,
    fats: 0,
    baseUnit: "1 scoop (5g)",
  },
  {
    nameEn: "Fish Oil Supplement",
    nameAr: "مكمل زيت السمك",
    calories: 40,
    protein: 0,
    carbs: 0,
    fats: 4.5,
    baseUnit: "1 tbsp (14g)",
  },
  {
    nameEn: "Taameya / Falafel",
    nameAr: "طعمية / فلافل",
    calories: 333,
    protein: 13,
    carbs: 31,
    fats: 18,
    baseUnit: "100g",
  },
  {
    nameEn: "Koshary",
    nameAr: "كشري",
    calories: 180,
    protein: 5,
    carbs: 35,
    fats: 4,
    baseUnit: "100g",
  },
  {
    nameEn: "Shawarma (Chicken)",
    nameAr: "شاورما دجاج",
    calories: 240,
    protein: 18,
    carbs: 10,
    fats: 15,
    baseUnit: "100g",
  },
  {
    nameEn: "Hummus",
    nameAr: "حمص",
    calories: 166,
    protein: 8,
    carbs: 14,
    fats: 9,
    baseUnit: "100g",
  },
  {
    nameEn: "Baba Ghanoush",
    nameAr: "بابا غنوج",
    calories: 120,
    protein: 3,
    carbs: 8,
    fats: 9,
    baseUnit: "100g",
  },
  {
    nameEn: "Labneh",
    nameAr: "لبنة",
    calories: 118,
    protein: 10,
    carbs: 3,
    fats: 8,
    baseUnit: "100g",
  },
  {
    nameEn: "Cottage Cheese (Areesh Style)",
    nameAr: "قريش / عريش",
    calories: 97,
    protein: 11,
    carbs: 3.8,
    fats: 4.7,
    baseUnit: "100g",
  },
  {
    nameEn: "Ful Medames",
    nameAr: "فول مدمس",
    calories: 110,
    protein: 8,
    carbs: 20,
    fats: 1,
    baseUnit: "100g",
  },
];

const run = async () => {
  try {
    await connectDB();
    await GlobalFood.deleteMany({});
    await GlobalFood.insertMany(foods);
    console.log(
      `✓ Seeded ${foods.length} GlobalFood records successfully to Atlas Database.`,
    );
    process.exit(0);
  } catch (error) {
    console.error("✗ Failed to seed GlobalFood", error);
    process.exit(1);
  }
};

run();
